# Generated by Django 4.2.7 on 2023-11-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antique', '0003_alter_customuser_managers_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='customuser',
        ),
    ]
