# Generated by Django 4.2.7 on 2023-11-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antique', '0004_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
