# Generated by Django 4.2.7 on 2023-11-30 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antique', '0006_customuser_is_active_customuser_is_stuff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_stuff',
            new_name='is_staff',
        ),
    ]
