# Generated by Django 4.2.7 on 2023-11-30 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antique', '0006_evaluation'),
        ('antique', '0007_rename_is_stuff_customuser_is_staff'),
    ]

    operations = [
    ]
