# Generated by Django 4.2.7 on 2023-11-30 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antique', '0006_evaluation'),
        ('antique', '0009_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
    ]
